openapi: 3.2.0
info:
  contact:
    x-twitter: JustEatUK
  description: '# Just Eat API

    Just Eat offers services for our various business partners and our consumer applications.'
  title: Just Eat UK Delivery Fee API
  version: 1.0.0
  x-apisguru-categories:
  - ecommerce
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_JustEatUK_profile_image.png
  x-origin:
  - format: openapi
    url: https://uk.api.just-eat.io/docs/openapi.json
    version: '3.0'
  x-providerName: just-eat.co.uk
servers:
- description: Production URL for the UK API
  url: https://uk.api.just-eat.io
- description: Production URL for the DK, ES, IE, IT and NO API
  url: https://i18n.api.just-eat.io
- description: Production URL for the AU and NZ API
  url: https://aus.api.just-eat.io
tags:
- name: Delivery fee
paths:
  /delivery-fees/{tenant}:
    get:
      description: Retrieve delivery fees for many restaurants. Returns fees and minimum order values required for delivery orders.
      parameters:
      - description: Tenant containing the restaurants.
        example: uk
        in: path
        name: tenant
        required: true
        schema:
          type: string
      - description: Restaurant IDs which fees are requested for. e.g. `?restaurantIds=1,2,3,4`
        example:
        - '1'
        - '2'
        - '3'
        - '4'
        explode: false
        in: query
        name: restaurantIds
        required: true
        schema:
          items:
            type: string
          maxItems: 200
          type: array
        style: form
      - description: Delivery date/time when fees are required (ISO8601 format).
        example: '2019-09-05T12:43:48.431Z'
        in: query
        name: deliveryTime
        required: true
        schema:
          format: date-time
          type: string
      - description: Postcode or other location name identifying the location to which delivery is required. For use when precise location is not available. This will be removed in future in favour of location.
        example: BS1
        in: query
        name: zone
        required: false
        schema:
          type: string
      - description: Point to which delivery is required (latitude, longitude). Supply this where possible as support for zone-only based lookups will be removed in future.
        example:
        - 51.3851513
        - -2.0841275
        explode: false
        in: query
        name: latlong
        required: false
        schema:
          items:
            format: double
            type: number
          maxItems: 2
          minItems: 2
          type: array
        style: form
      responses:
        '200':
          content:
            application/json:
              examples:
                flatRate:
                  summary: Single fee, with and without minimum order value
                  value:
                    restaurants:
                    - bands:
                      - fee: 250
                        minimumAmount: 1000
                      minimumOrderValue: 1000
                      restaurantId: '1234'
                    - bands:
                      - fee: 100
                        minimumAmount: 0
                      minimumOrderValue: 0
                      restaurantId: '5678'
                flatRateWithFreeTier:
                  summary: Single fee with minimum order value, and free delivery threshold
                  value:
                    restaurants:
                    - bands:
                      - fee: 250
                        minimumAmount: 1000
                      - fee: 0
                        minimumAmount: 2000
                      minimumOrderValue: 1000
                      restaurantId: '1234'
                threeTier:
                  summary: No minimum order value, three pricing tiers
                  value:
                    restaurants:
                    - bands:
                      - fee: 250
                        minimumAmount: 0
                      - fee: 100
                        minimumAmount: 10
                      - fee: 0
                        minimumAmount: 2000
                      minimumOrderValue: 0
                      restaurantId: '1234'
              schema:
                properties:
                  restaurants:
                    description: Collection of restaurants for which delivery fees were found.
                    items:
                      $ref: '#/components/schemas/RestaurantDeliveryFees'
                    type: array
                type:
                - object
                - 'null'
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
      summary: Get restaurant delivery fees
      tags:
      - Delivery fee
      operationId: getDeliveryFeesByTenant
      x-operation-id-source: derived
components:
  schemas:
    RestaurantDeliveryFees:
      example:
        bands:
        - fee: 250
          minimumAmount: 1000
        - fee: 0
          minimumAmount: 2000
        minimumOrderValue: 1000
        restaurantId: '5678'
      properties:
        bands:
          description: Collection of delivery fee bands
          items:
            properties:
              fee:
                description: The delivery fee, in the smallest unit of local currency (e.g. pence).
                format: integer
                type: number
              minimumAmount:
                description: The minimum order value (excluding fees) when this fee band applies. The fee with the highest `minimumAmount` that is less than or equal to order value applies. This is in the smallest unit of local currency (e.g. pence).
                format: integer
                type: number
            type: object
          type: array
        minimumOrderValue:
          description: The minimum order value (excluding fees) required, in the smallest unit of local currency (e.g. pence).
          format: integer
          type: number
        restaurantId:
          description: The identifier of the restaurant
          type: string
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      description: Bearer token authentication using a JSON Web Token (JWT).
      scheme: bearer
      type: http
    api_key:
      description: APIs for delivery partners require an API key that will have been issued to you.
      in: header
      name: Authorization
      type: apiKey
    basic_auth:
      description: A few services allow the use of basic authentication when a partner doesn't support OAuth based authentication.
      scheme: basic
      type: http
    justeat_adfs:
      description: ADFS authentication provider for internal Just Eat tools.
      openIdConnectUrl: https://adfs.just-eat.com/adfs/.well-known/openid-configuration
      type: openIdConnect
    restaurantsignup_jwt:
      bearerFormat: JWT token with payload `RestaurantId` and Role `[RestaurantRead | VerifyEmail | RestaurantWrite | FullAccess | DocumentRead]`
      description: Bearer token authentication using a JSON Web Token (JWT), used by the restaurant sign up system
      scheme: bearer
      type: http
x-tagGroups:
- name: Consumer Experience
  tags:
  - Authorization
  - Consumers
  - ConsumerOffers
  - ConsumerQueries
  - Consumer Queries Webhooks
  - ConsumerOrders
  - Search
  - Basket
  - Payments
  - Giftcards
  - Experiments
  - Vouchers
  - Promoted Placement
  - Menu
  - Recommendations
  - Location Services
- name: Manage Order Journey
  tags:
  - Order Acceptance API
  - Order Acceptance Webhooks
  - Order Delivery API
  - Order Delivery Webhooks
  - Order API
  - Order Webhooks
  - Customer Order Details
  - DeliveryFee
  - Delivery Pools API
  - Attempted Delivery API
  - Attempted Delivery Webhooks
  - Checkout
  - Courier Feedback
- name: Restaurant Management
  tags:
  - Restaurant Product
  - Restaurants
  - RestaurantOffers
  - Restaurant OrderTimes
  - Restaurants Webhooks
  - RestaurantSignup
  - RestaurantQueries
  - RestaurantQueries Webhooks
  - Restaurant Claims
  - Restaurant Events
  - Restaurant Events Webhooks
  - Restaurant API
  - Restaurant Webhooks
  - Products
  - Logistics POS Restaurants
  - Restaurant Smiley Rating
