openapi: 3.2.0
info:
  contact:
    x-twitter: JustEatUK
  description: '# Just Eat API

    Just Eat offers services for our various business partners and our consumer applications.'
  title: Just Eat UK Order Acceptance Webhooks API
  version: 1.0.0
  x-apisguru-categories:
  - ecommerce
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_JustEatUK_profile_image.png
  x-origin:
  - format: openapi
    url: https://uk.api.just-eat.io/docs/openapi.json
    version: '3.0'
  x-providerName: just-eat.co.uk
servers:
- description: Production URL for the UK API
  url: https://uk.api.just-eat.io
- description: Production URL for the DK, ES, IE, IT and NO API
  url: https://i18n.api.just-eat.io
- description: Production URL for the AU and NZ API
  url: https://aus.api.just-eat.io
tags:
- name: Order Acceptance Webhooks
paths:
  /acceptance-requested:
    post:
      description: This webhook will be invoked whenever acceptance has been requested for the order.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/acceptance-requested'
        required: true
      responses:
        '200':
          description: Respond with a 200 status code to indicate that you have received the notification.
      summary: Acceptance requested
      tags:
      - Order Acceptance Webhooks
      operationId: postAcceptanceRequested
      x-operation-id-source: derived
  /order-accepted:
    post:
      description: This webhook will be invoked whenever the order was accepted.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order-accepted'
        required: true
      responses:
        '200':
          description: Respond with a 200 status code to indicate that you have received the notification.
      summary: Order accepted
      tags:
      - Order Acceptance Webhooks
      operationId: postOrderAccepted
      x-operation-id-source: derived
  /order-cancelled:
    post:
      description: This webhook will be invoked whenever the order was cancelled.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order-cancelled'
        required: true
      responses:
        '200':
          description: Respond with a 200 status code to indicate that you have received the notification.
      summary: Order cancelled
      tags:
      - Order Acceptance Webhooks
      operationId: postOrderCancelled
      x-operation-id-source: derived
  /order-rejected:
    post:
      description: This webhook will be invoked whenever the order was rejected.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order-rejected'
        required: true
      responses:
        '200':
          description: Respond with a 200 status code to indicate that you have received the notification.
      summary: Order rejected
      tags:
      - Order Acceptance Webhooks
      operationId: postOrderRejected
      x-operation-id-source: derived
  /redelivery-requested:
    put:
      description: This webhook will be invoked whenever the customer responds to the attempted delivery notification.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/attempted-delivery-response-received'
        required: true
      responses:
        '200':
          description: Respond with a 200 status code to indicate that you have received the notification.
      summary: Customer Requested Redelivery
      tags:
      - Order Acceptance Webhooks
      operationId: putRedeliveryRequested
      x-operation-id-source: derived
components:
  schemas:
    order-cancelled:
      example:
        Event: OrderCancelled
        OrderId: ijdhpy7bdusgtc28bapspa
        Reason: system_cancelled_other
      properties:
        Event:
          type: string
        OrderId:
          type: string
        Reason:
          description: The reason the order was cancelled.
          enum:
          - cust_cancelled_changed_mind
          - cust_cancelled_delivery_too_long
          - cust_cancelled_made_mistake
          - cust_cancelled_other
          - delivery_partner_cancelled
          - rest_cancelled_customer_absent
          - rest_cancelled_customer_requested
          - rest_cancelled_declined
          - rest_cancelled_drivers_unavailable
          - rest_cancelled_fake_order
          - rest_cancelled_other
          - rest_cancelled_out_of_stock
          - rest_cancelled_too_busy
          - system_cancelled_other
          - system_cancelled_test_order
          type: string
      type: object
    acceptance-requested:
      example:
        Currency: GBP
        Customer:
          Id: 12345
          Name: Bruce Wayne
          PreviousRestaurantOrderCount: 5
          PreviousTotalOrderCount: 83
        CustomerNotes:
          noteForDelivery: delivery note
          noteForRestaurant: restaurant note
        FriendlyOrderReference: REF0001
        Fulfilment:
          Address:
            City: London
            Geolocation:
              Latitude: 51.51641
              Longitude: -0.103198
            Lines:
            - Fleet Place House
            - Fleet Pl
            PostalCode: EC4M 7RD
          CustomerDueAsap: false
          CustomerDueDate: '2018-03-10T14:45:28Z'
          Method: Delivery
          PhoneMaskingCode: '9999999'
          PhoneNumber: '+441234567890'
          PreparationTime: 0:23:32
        IsTest: true
        Items:
        - Items:
          - Items: []
            Name: Fries
            Quantity: 1
            Reference: '9876'
            Synonym: Regular
            UnitPrice: 0
          - Items: []
            Name: Pepsi
            Quantity: 2
            Reference: '6789'
            Synonym: 330ml
            UnitPrice: 0
          Name: Chicken Box Meal
          Quantity: 2
          Reference: '1234'
          Synonym: ''
          TotalPrice: 10
          UnitPrice: 5
        - Items: []
          Name: Milkshake
          Quantity: 1
          Reference: '4321'
          Synonym: ''
          TotalPrice: 7.25
          UnitPrice: 7.25
        OrderId: ABCD654321
        Payment:
          Lines:
          - Paid: false
            Type: AccountCredit
            Value: 19.25
          - Paid: true
            Type: CreditCard
            Value: 19.25
        PlacedDate: '2018-03-10T14:45:28Z'
        PriceBreakdown:
          Discount: 0
          Fees:
            Delivery: 1
            Other: 0
            ServiceCharge: 0.5
          Items: 17.25
          Taxes: 3.85
          Tips: 0.5
        Restaurant:
          Address:
            City: London
            Geolocation:
              Latitude: 51.4484
              Longitude: -0.1504
            Lines:
            - Oldridge Road
            PostalCode: SW12 8PW
          Id: I12345
          Name: Just Eat Test Restaurant
          PhoneNumber: '+441200000000'
          Refererence: R99999
          TimeZone: Australia/Sydney (IANA format)
        Restrictions:
        - Type: Alcohol
        TotalPrice: 19.25
      properties:
        Currency:
          type: string
        Customer:
          properties:
            Id:
              type:
              - number
              - 'null'
            Name:
              type: string
            PreviousRestaurantOrderCount:
              description: The customer's previous total number of orders made to this restaurant
              type: number
            PreviousTotalOrderCount:
              description: The customer's previous total number of orders made to all restaurants
              type: number
          type: object
        CustomerNotes:
          additionalProperties:
            type: string
          type: object
        FriendlyOrderReference:
          type: string
        Fulfilment:
          properties:
            Address:
              $ref: '#/components/schemas/order-address'
            CustomerDueAsap:
              type: boolean
            CustomerDueDate:
              format: date-time
              type: string
            Method:
              enum:
              - Delivery
              - Collection
              type: string
            PhoneMaskingCode:
              description: Code to use when calling customer phone masking number about this order. null if phone masking not enabled
              type: string
            PhoneNumber:
              description: Customer phone number (will be phone masking number if enabled)
              type: string
            PreparationTime:
              format: timespan
              type: string
          type: object
        IsTest:
          type: boolean
        Items:
          $ref: '#/components/schemas/order-item'
        OrderId:
          type: string
        Payment:
          properties:
            Lines:
              items:
                properties:
                  Paid:
                    type: boolean
                  Type:
                    type: string
                  Value:
                    format: money
                    type: number
                type: object
              type: array
          type: object
        PlacedDate:
          format: date-time
          type: string
        PriceBreakdown:
          properties:
            Discount:
              format: money
              type:
              - number
              - 'null'
            Fees:
              properties:
                Delivery:
                  format: money
                  type:
                  - number
                  - 'null'
                Other:
                  format: money
                  type:
                  - number
                  - 'null'
                ServiceCharge:
                  format: money
                  type:
                  - number
                  - 'null'
              type: object
            Items:
              format: money
              type:
              - number
              - 'null'
            Taxes:
              format: money
              type:
              - number
              - 'null'
            Tips:
              format: money
              type:
              - number
              - 'null'
          type: object
        Restaurant:
          properties:
            Address:
              $ref: '#/components/schemas/order-address'
            Id:
              description: Restaurant Id
              type: string
            Name:
              type: string
            PhoneNumber:
              type: string
            Reference:
              type: string
            TimeZone:
              type: string
          type: object
        Restrictions:
          description: This is a list of types of restricted items contained in the order.
          items:
            $ref: '#/components/schemas/order-item-restriction'
          type: array
        TotalPrice:
          format: money
          type: number
      type: object
    order-address:
      properties:
        City:
          type: string
        Geolocation:
          properties:
            Latitude:
              format: double
              type: number
            Longitude:
              format: double
              type: number
          type: object
        Lines:
          items:
            type: string
          type: array
        PostalCode:
          type: string
      type: object
    order-item:
      items:
        properties:
          Items:
            $ref: '#/components/schemas/order-item'
          Name:
            type: string
          Quantity:
            type: number
          Reference:
            type: string
          TotalPrice:
            format: money
            type: number
          UnitPrice:
            format: money
            type: number
        type: object
      type: array
    attempted-delivery-response-received:
      example:
        Notes: Please press 123 on the door
        OrderId: wiej234idf09i29jijgf4
        Tenant: uk
        Update: Please redeliver
      properties:
        Notes:
          type: string
        OrderId:
          type: string
        Tenant:
          type: string
        Update:
          type: string
      type: object
    order-accepted:
      example:
        AcceptedFor: '2018-03-10T14:45:28Z'
        Event: OrderAccepted
        OrderId: '123456'
      properties:
        AcceptedFor:
          format: date-time
          type: string
        Event:
          type: string
        OrderId:
          type: string
      type: object
    order-item-restriction:
      properties:
        Type:
          description: The type of restricted item contained in the order. The only supported value is 'Alcohol'.
          enum:
          - Alcohol
          type: string
      type: object
    order-rejected:
      example:
        Event: OrderRejected
        RejectedAt: '2018-03-10T14:45:28Z'
        RejectedBy: '123456'
        RejectedReason: Kitchen overloaded
      properties:
        Event:
          type: string
        RejectedAt:
          format: date-time
          type: string
        RejectedBy:
          type: string
        RejectedReason:
          type: string
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      description: Bearer token authentication using a JSON Web Token (JWT).
      scheme: bearer
      type: http
    api_key:
      description: APIs for delivery partners require an API key that will have been issued to you.
      in: header
      name: Authorization
      type: apiKey
    basic_auth:
      description: A few services allow the use of basic authentication when a partner doesn't support OAuth based authentication.
      scheme: basic
      type: http
    justeat_adfs:
      description: ADFS authentication provider for internal Just Eat tools.
      openIdConnectUrl: https://adfs.just-eat.com/adfs/.well-known/openid-configuration
      type: openIdConnect
    restaurantsignup_jwt:
      bearerFormat: JWT token with payload `RestaurantId` and Role `[RestaurantRead | VerifyEmail | RestaurantWrite | FullAccess | DocumentRead]`
      description: Bearer token authentication using a JSON Web Token (JWT), used by the restaurant sign up system
      scheme: bearer
      type: http
x-tagGroups:
- name: Consumer Experience
  tags:
  - Authorization
  - Consumers
  - ConsumerOffers
  - ConsumerQueries
  - Consumer Queries Webhooks
  - ConsumerOrders
  - Search
  - Basket
  - Payments
  - Giftcards
  - Experiments
  - Vouchers
  - Promoted Placement
  - Menu
  - Recommendations
  - Location Services
- name: Manage Order Journey
  tags:
  - Order Acceptance API
  - Order Acceptance Webhooks
  - Order Delivery API
  - Order Delivery Webhooks
  - Order API
  - Order Webhooks
  - Customer Order Details
  - DeliveryFee
  - Delivery Pools API
  - Attempted Delivery API
  - Attempted Delivery Webhooks
  - Checkout
  - Courier Feedback
- name: Restaurant Management
  tags:
  - Restaurant Product
  - Restaurants
  - RestaurantOffers
  - Restaurant OrderTimes
  - Restaurants Webhooks
  - RestaurantSignup
  - RestaurantQueries
  - RestaurantQueries Webhooks
  - Restaurant Claims
  - Restaurant Events
  - Restaurant Events Webhooks
  - Restaurant API
  - Restaurant Webhooks
  - Products
  - Logistics POS Restaurants
  - Restaurant Smiley Rating
